---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/consultacvd.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_consultacvd/
      - /bin/rsync -av ./ $DEPLOYPATH

